#!/bin/sh
FWROOT="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
export FWROOT
cd $FWROOT
# for some reason ". environ" always fails in pbuilder with "environ: not found"
. $FWROOT/environ
ARCH=$(uname -m)
mkdir -p Output_$ARCH/VarLibFieldworks
mkdir -p DistFiles/Templates
cd Bld
nant "$@" localize
